import type { AppState } from '../types';

// Today is ~Feb 23, 2026
// Bob joined Dec 1, 2025  → ~84 days ago
// Carol joined Jan 15, 2026 → ~39 days ago

export const SEED_DATA: AppState = {
  currentUserId: null,
  adminMode: false,
  users: [
    {
      id: 'user-1',
      name: 'Alice Admin',
      email: 'alice@company.com',
      role: 'ADMIN',
      password: 'admin123',
      image: '',
      joinDate: '2023-01-10',
      department: 'Management',
      position: 'HR Manager',
      phone: '+62 812-0000-0001',
    },
    {
      id: 'user-2',
      name: 'Bob User',
      email: 'bob@company.com',
      role: 'USER',
      password: 'user123',
      image: '',
      joinDate: '2025-12-01',
      department: 'Engineering',
      position: 'Frontend Developer',
      phone: '+62 812-0000-0002',
    },
    {
      id: 'user-3',
      name: 'Carol User',
      email: 'carol@company.com',
      role: 'USER',
      password: 'user123',
      image: '',
      joinDate: '2026-01-15',
      department: 'Design',
      position: 'UI/UX Designer',
      phone: '+62 812-0000-0003',
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Company Onboarding',
      createdById: 'user-1',
      includeOpeningPage: true,
      openingCoverUrl:
        'https://images.unsplash.com/photo-1573717865061-202c78c4b414?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
      openingCaption: 'Welcome to the team! We are so excited to have you here.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-2',
      title: 'Meet Your Team',
      createdById: 'user-1',
      includeOpeningPage: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-3',
      title: '30-Day Check-In',
      createdById: 'user-1',
      includeOpeningPage: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-4',
      title: '60-Day Goals Review',
      createdById: 'user-1',
      includeOpeningPage: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  pages: [
    {
      id: 'page-1',
      taskId: 'task-1',
      index: 0,
      title: 'Welcome',
    },
    {
      id: 'page-2',
      taskId: 'task-1',
      index: 1,
      title: 'About Us',
    },
    {
      id: 'page-3',
      taskId: 'task-2',
      index: 0,
      title: 'Your Team',
    },
    {
      id: 'page-4',
      taskId: 'task-3',
      index: 0,
      title: 'Check-In',
    },
    {
      id: 'page-5',
      taskId: 'task-4',
      index: 0,
      title: 'Goals Review',
    },
  ],
  sections: [
    {
      id: 'section-1',
      pageId: 'page-1',
      index: 0,
      type: 'TEXT_BOX',
      colorTheme: 'DEFAULT',
      data: {
        content:
          '<h1>Welcome to the Team!</h1><p>We are thrilled to have you join us. This onboarding will walk you through everything you need to know to get started successfully.</p>',
      },
      required: false,
    },
    {
      id: 'section-2',
      pageId: 'page-1',
      index: 1,
      type: 'YOUTUBE',
      colorTheme: 'DEFAULT',
      data: {
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      },
      required: false,
    },
    {
      id: 'section-3',
      pageId: 'page-1',
      index: 2,
      type: 'YES_NO',
      colorTheme: 'PRIMARY_TINT',
      data: {
        question: 'Are you ready to get started with your onboarding?',
        correctAnswer: true,
      },
      required: true,
    },
    {
      id: 'section-4',
      pageId: 'page-2',
      index: 0,
      type: 'TEXT_BOX',
      colorTheme: 'DEFAULT',
      data: {
        content:
          '<h2>Our Mission</h2><p>We build products that make people\'s lives easier, connecting teams and enabling collaboration at scale.</p><blockquote>Innovation is not just a value — it\'s how we work every day.</blockquote>',
      },
      required: false,
    },
    {
      id: 'section-5',
      pageId: 'page-2',
      index: 1,
      type: 'MULTIPLE_CHOICE',
      colorTheme: 'DEFAULT',
      data: {
        question: "What best describes our company's primary mission?",
        options: [
          { id: 'opt-a', label: 'Build great products that help people' },
          { id: 'opt-b', label: 'Maximize quarterly profits' },
          { id: 'opt-c', label: 'Compete with every other company' },
        ],
        correctOptionId: 'opt-a',
      },
      required: true,
    },
    {
      id: 'section-6',
      pageId: 'page-2',
      index: 2,
      type: 'ESSAY',
      colorTheme: 'ACCENT_TINT',
      data: {
        prompt: 'Introduce yourself to the team!',
        placeholder:
          'Tell us a bit about yourself, your background, and what excites you most about joining...',
        maxLength: 500,
      },
      required: true,
    },
    {
      id: 'section-7',
      pageId: 'page-3',
      index: 0,
      type: 'TEXT_BOX',
      colorTheme: 'DEFAULT',
      data: {
        content: '<h2>Meet the Team</h2><p>Get to know your colleagues and learn about the different departments.</p>',
      },
      required: false,
    },
    {
      id: 'section-8',
      pageId: 'page-4',
      index: 0,
      type: 'ESSAY',
      colorTheme: 'ACCENT_TINT',
      data: {
        prompt: 'How are you feeling after your first 30 days?',
        placeholder: 'Share your thoughts, challenges, and wins...',
        maxLength: 800,
      },
      required: true,
    },
    {
      id: 'section-9',
      pageId: 'page-5',
      index: 0,
      type: 'ESSAY',
      colorTheme: 'PRIMARY_TINT',
      data: {
        prompt: 'What are your goals for the next 60 days?',
        placeholder: 'Describe your goals and how you plan to achieve them...',
        maxLength: 800,
      },
      required: true,
    },
  ],
  // User task groups define sections and locking
  // Bob (84 days) → groups 1–3 auto-unlocked; group 4 (60 days) also unlocked
  // Carol (39 days) → groups 1–2 auto-unlocked; group 3 (30 days) unlocked; group 4 (60 days) still LOCKED
  userTaskGroups: [
    {
      userId: 'user-2',
      groups: [
        {
          id: 'grp-b1',
          name: 'Your First Day',
          taskIds: ['task-1'],
          locked: false,
          unlockAfterDays: null,
        },
        {
          id: 'grp-b2',
          name: 'Your First Week',
          taskIds: ['task-2'],
          locked: true,
          unlockAfterDays: 7,
        },
        {
          id: 'grp-b3',
          name: 'First 30 Days',
          taskIds: ['task-3'],
          locked: true,
          unlockAfterDays: 30,
        },
        {
          id: 'grp-b4',
          name: 'First 60 Days',
          taskIds: ['task-4'],
          locked: true,
          unlockAfterDays: 60,
        },
      ],
    },
    {
      userId: 'user-3',
      groups: [
        {
          id: 'grp-c1',
          name: 'Your First Day',
          taskIds: ['task-1'],
          locked: false,
          unlockAfterDays: null,
        },
        {
          id: 'grp-c2',
          name: 'Your First Week',
          taskIds: ['task-2'],
          locked: true,
          unlockAfterDays: 7,
        },
        {
          id: 'grp-c3',
          name: 'First 30 Days',
          taskIds: ['task-3'],
          locked: true,
          unlockAfterDays: 30,
        },
        {
          id: 'grp-c4',
          name: 'First 60 Days',
          taskIds: ['task-4'],
          locked: true,
          unlockAfterDays: 60,
        },
      ],
    },
  ],
  assignments: [
    {
      id: 'assign-1',
      userId: 'user-2',
      taskId: 'task-1',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-2',
      userId: 'user-2',
      taskId: 'task-2',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-3',
      userId: 'user-2',
      taskId: 'task-3',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-4',
      userId: 'user-2',
      taskId: 'task-4',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-5',
      userId: 'user-3',
      taskId: 'task-1',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-6',
      userId: 'user-3',
      taskId: 'task-2',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-7',
      userId: 'user-3',
      taskId: 'task-3',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'assign-8',
      userId: 'user-3',
      taskId: 'task-4',
      status: 'NOT_STARTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  answers: [],
};
